### ISSUE TITLE
Gradle and import android-saripaar:2.0-SNAPSHOT

### ISSUE THREAD

**Issue by agusgambina** [ragunathjawahar/android-saripaar#100]
I have been using this project like from 6 months, and I like it. But today this happened

I have this in my build.gradle inside my folder app
```
dependencies {
  compile 'com.mobsandgeeks:android-saripaar:2.0-SNAPSHOT'
}
```
and this in build.gradle at the root folder of the project
```
maven {
  url "https://oss.sonatype.org/content/repositories/
}
```
But today when I cleaned my project and made the sync with gradle, seems is not importing the library anymore.

In every class I use dependencies of this library, it can not make the imports, it seems that it does not find them, for example

```
import com.mobsandgeeks.saripaar.ValidationError;
import com.mobsandgeeks.saripaar.Validator;
import com.mobsandgeeks.saripaar.annotation.ConfirmPassword;
import com.mobsandgeeks.saripaar.annotation.Email;
import com.mobsandgeeks.saripaar.annotation.Order;
import com.mobsandgeeks.saripaar.annotation.Password;
import com.mobsandgeeks.saripaar.annotation.Size;
```

Thank you

**Comment by ragunathjawahar** [comment]
:confused: I checked and I don't see any problem in my IDE, one breaking change is that `@Size` has been renamed to `@Length`. Another developer confirmed a successful build too. Can you share specific error messages?

**Comment by agusgambina** [comment]
Thank you for your quick response.

I am using Ubuntu 14.10, Android Studio 1.2.2, just for the record. Gradle doesn't throw me any error about importing the library (seems to be working), but in the classes cannot resolve the imports

![registry](https://cloud.githubusercontent.com/assets/2176582/8961557/4e475732-35ec-11e5-9970-1d3074baf07c.png)

**Comment by agusgambina** [comment]
Seems it was the IDE, I closed the project and reopened and it worked.

**Comment by ragunathjawahar** [comment]
@agusgambina Ok great!
