### ISSUE TITLE
Validate Only If Fields Are Not Empty

### ISSUE THREAD

**Issue by meNESS** [ragunathjawahar/android-saripaar#102]
Hi,

Is there anyway to tell Saripaar to validate fields only if they're not empty? If not, please implement this feature.

Thanks for this great library.

**Comment by ragunathjawahar** [comment]
Hi, there'll be an `@Optional` annotation to facilitate this in the next release. You're welcome BTW.

**Comment by herghost** [comment]
@ragunathjawahar Any news on the next release, I also require this and echo @alirezaaa comments on a great library :-)

**Comment by herghost** [comment]
As a work around for now, I have changed anything I required that is optional to the pattern match and just added '^$'

**Comment by ragunathjawahar** [comment]
@herghost Thank you, I don't have a timeline on this yet. But will post updates on this thread.

**Comment by nazeels** [comment]
Hey @ragunathjawahar is this fixed

**Comment by ragunathjawahar** [comment]
@nazeels it isn't. I accidentally slipped the `@Optional` annotation into the release build. It isn't functional yet. It will be in the next release.

**Comment by PranKe01** [comment]
Any new informations when the new version will be released? I also need optional validation :|

**Comment by robinsingh-bw** [comment]
Wondering the same, any news on the optional annotation?

**Comment by meNESS** [comment]
@robinsingh-bw Unfortunately @ragunathjawahar (the owner) doesn't work on his great library anymore.

**Comment by ragunathjawahar** [comment]
On commit https://github.com/ragunathjawahar/android-saripaar/commit/b8626e97794fb2b797b33679b00453fb14320bfe, awaiting release.

**Comment by ashraffouad** [comment]
I hope this to be released soon, release 2.1.0 is still having 4 open issues.

**Comment by riinav** [comment]
@ragunathjawahar Is is possible to release Snapshot build with Optional Annotation, before 2.1.0?

**Comment by ragunathjawahar** [comment]
@riinav `2.1.0-SNAPSHOT` available with this feature.

**Comment by ashraffouad** [comment]
Any news about release 2.1.0?

**Comment by Wounded-Shadow** [comment]
2.1.0 still not available?
