### ISSUE TITLE
RadioGroup Validation using @Checked 

### ISSUE THREAD

**Issue by syr** [ragunathjawahar/android-saripaar#103]
Hello,
would be nice if also RadioGroups would be validated by annotation @Checked.

**Comment by ragunathjawahar** [comment]
Works, can you recheck?

**Comment by ragunathjawahar** [comment]
Already fixed, same as #78

**Comment by syr** [comment]
Sorry, mis-used the framework. It works now. However, how to set encoding für @Checked(message?

**Comment by ragunathjawahar** [comment]
Do you mean string resources?

**Comment by syr** [comment]
Ok, that was a bit too brief..sorry.

I have something linke this: `@Checked(message = "öäüß")`

Instead of the characters there are only questionmarks in the Toast output.

Btw.: Is there a way to reference string resources and assign them to message like this or maybe similar to?:
`@Checked(message = @string/myStringMessage)`

**Comment by ragunathjawahar** [comment]
Use the `messageResId` attribute instead of `message`

**Comment by syr** [comment]
oops I should have seen that...perfect..thanks.
