### ISSUE TITLE
Button hint is counted as not empty

### ISSUE THREAD

**Issue by woodcockjosh** [ragunathjawahar/android-saripaar#105]
Validation passes for @NotEmpty when button hint is set. This should only pass validation when button text is set.

**Comment by ragunathjawahar** [comment]
Fixed in d0f70b620d132e2335ecff0e1b93c3dee3e29998, `@NotEmpty` annotation now has `emptyText` and `emptyTextResId` attributes.

**Comment by woodcockjosh** [comment]
is this released?

On Fri, Sep 18, 2015 at 12:11 AM, Ragunath Jawahar <notifications@github.com

**Comment by ragunathjawahar** [comment]
Yes, version 2.0.3
