### ISSUE TITLE
Let validate() return List<ValidationError>

### ISSUE THREAD

**Issue by syr** [ragunathjawahar/android-saripaar#106]
Would be nice if there would be a validate method override of `List<ValidationError> validate()`.

Currently I'm setting a field of `List<ValidationError> validationErrorList;` by callback method like that:
`void onValidationFailed(List<ValidationError> list){`
`validationErrorList = list;`
`}`

**Comment by ragunathjawahar** [comment]
@syr sorry, we won't be doing this.

1. You have to do a null check or an empty list check if the validation passes.
2. This does not isolate the validation pass and validation failed logic.
3. With the current API switching to an async validation is seamless. I don't want users to remember / use two different methods for validation.

**Comment by syr** [comment]
@ragunathjawahar: Hi thanks for the quick feedback.

to 1st point: null-check and empty list check is not neccessary if `validate()` always returns a list even when it's empty. So one could iterate over it by foreach for example without that checks.
Btw. Returning null is bad ;-) (see described in Clean Code: A Handbook of Agile Software Craftsmanship (Robert C. Martin) and all over the net.)  

to 2nd point: when `validate()` returns a list then validation logic is already processed.. subsequently  another method could handle the validation errors. I think that's sufficiently isolated.

to 3rd point: I think that's a matter of taste. One could have validate() and validateAsync(), or even passing a boolean isAsync..btw. which however is not best code style. In my opinion I prefer to see in code if its sync. or async. especially when extending code of a collleague.

Cheers,
Christian

**Comment by syr** [comment]
Just worked around by inheriting Validator by 
`public class ActivityValidator extends Validator implements Validator.ValidationListener` ..in that way that in any activity I just have to write a one liner bevore saving like this:

`if(new ActivityValidator(this).validationFailed()){ break; }`
