### ISSUE TITLE
Validation on Dialog View 

### ISSUE THREAD

**Issue by xrnd** [ragunathjawahar/android-saripaar#107]
How to do validation on fields present in dialog.
As Validator is initialised either using activity/Fragment, I get an error displaying 
"You must have at least one rule to validate. If you are using custom annotations, make sure that you have registered them using the 'Validator.register()' method."
I have set annotation but they are not identified by Validator.

Thanks

**Comment by ragunathjawahar** [comment]
@xrnd Can you please paste some sample code?

**Comment by ragunathjawahar** [comment]
What are you passing to the validator? The dialog instance or the activity? The Validator accepts the object that contains the annotated fields. If your fields are declared and annotated inside the dialog class. You should pass the dialog to the constructor.

**Comment by xrnd** [comment]
Hi,
I am using default Dialog class instance but my dialog fields are declared in activity and annotated. I first passed dialog instance since fields are in that, but realised from your answer that they are declared in Activity so I need to pass activity instance. Thanks alot @ragunathjawahar .

**Comment by ragunathjawahar** [comment]
@xrnd, you're welcome.
