### ISSUE TITLE
Attach views to a validator ?

### ISSUE THREAD

**Issue by Narayane** [ragunathjawahar/android-saripaar#109]
Hi,

in a single screen, I have a login and a sign up forms.

I wonder if it was possible to "attach" login views to a login validator (same for sign up) which would allow to only validate relative views and not all the views of the screen on mLoginValidator.validate().

e. g. something like that:

mLoginValidator = new Validator(this);
mLoginValidator.setValidationListener(mLoginValidationListener);
mLoginValidator.attach(mEditTextLoginEmail);
mLoginValidator.attach(mEditTextLoginPassword);

Best regards.

**Comment by Kikju** [comment]
Few days ago, I dealt with similar problem.
See https://github.com/ragunathjawahar/android-saripaar/issues/104

**Comment by Narayane** [comment]
Hi @Kikju 

maybe in this case attach validator to annotation as:

@NotEmpty(validator = mLoginValidator, ...)
private EditText mEditTextLoginEmail;

**Comment by Kikju** [comment]
No, you problem is as same as my...
Just write two classes, provide views into this classes and both of classes have own validator object... And if you want, validation listener can be same for both of them

**Comment by ragunathjawahar** [comment]
@Narayane @Kikju is right. Check issue #104

**Comment by Narayane** [comment]
Hi,

not sure second class creation to validate only 2 fields be the most efficient solution.

Thanks anyway.
