### ISSUE TITLE
Showing all the failed results of a particular view

### ISSUE THREAD

**Issue by ImMathanR** [ragunathjawahar/android-saripaar#110]
These are the rules I have added for the view.

@NotEmpty(sequence = 1, message = "Please enter Email Id")
    @Email(sequence = 2, message = "Please enter valid Email Id")
    @Order(3)
    @Bind(R.id.email)
    EditText mEmail;

In onValidationFailed method I try to get the error like 

errors.get(0).getCollatedErrorMessage(context);

Here I am getting both the Error messages in a single string.  

But is it possible to get the first hit error message from the particular view. Like if I try to validate the view without typing anything. It should show only the "Please enter Email id". After that if I typed something which was not email id, then only it should give the error message as "Please enter valid Email id". Is it possible with this version?

**Comment by ragunathjawahar** [comment]
You could do the following to achieve the desired result.

```java
List<Rule> failedRules = errors.get(0).getFailedRules();
String firstFailureMessage = failedRules.get(0).getMessage(context);
```
