### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by thomasbeerten** [ragunathjawahar/android-saripaar#111]
Great library, makes validation extremely clean!
I was wondering if there is a way to localize the error messages you annotate?

In my fragment I use Butterknife:

@NotEmpty(message = "This field can't be empty!!")
@Bind(R.id.txtTeamname)
EditText txtTeamname;

At that point in code, I can't reach my resources, to get to my Strings file. Any suggestions?

**Comment by Kikju** [comment]
you can use @NotEmpty(messageResId = R.string.text)
Dňa 2.9.2015 18:04 používateľ "thomasbeerten" <notifications@github.com>
napísal:

**Comment by ragunathjawahar** [comment]
@Kikju is right. @thomasbeerten use the `messageResId` attribute.
