### ISSUE TITLE
Multiple validations

### ISSUE THREAD

**Issue by herghost** [ragunathjawahar/android-saripaar#112]
Is there a way to have multiple validations for a form?

For instance I have a example where certain fields on my form are required if a condition is met, but should be ignored otherwise.

How would I go about achieving this?

**Comment by Kikju** [comment]
check this https://github.com/ragunathjawahar/android-saripaar/issues/104
You can have separate forms and conditions...

**Comment by herghost** [comment]
@Kikju - Fantastic, thanks!
