### ISSUE TITLE
Checked annotation for Switch view component.

### ISSUE THREAD

**Issue by Zapnologica** [ragunathjawahar/android-saripaar#114]
I tried the following:

   `@Checked(message = "You must agree to the terms.")
    private Switch switchTerms;`

and I got the following exception:

  `java.lang.UnsupportedOperationException: To use 'com.mobsandgeeks.saripaar.annotation.Checked' on 'android.widget.Switch', register a 'com.mobsandgeeks.saripaar.adapter.ViewDataAdapter' that returns a 'java.lang.Boolean' from the 'android.widget.Switch'.`

**Comment by ragunathjawahar** [comment]
````java
public class SwitchBooleanAdapter implements ViewDataAdapter<Switch, Boolean> {

    @Override
    public Boolean getData(final Switch aSwitch) {
        return aSwitch.isChecked();
    }
}
````

Register your adapter with your validator
````java
mValidator.registerAdapter(Switch.class, new SwitchBooleanAdapter());
````

`SwitchBooleanAdapter` will be available out-of-the-box in future releases. The current snapshot `(2.1.0-SNAPSHOT)` has it, therefore no explict registration required if you are going to use it.

**Comment by Zapnologica** [comment]
Thanks for the feedback. I will wait for it to be out of the box as it is not currently a necessity.
