### ISSUE TITLE
Dynamic validation

### ISSUE THREAD

**Issue by ronakamlani** [ragunathjawahar/android-saripaar#116]
Hello, first of all thank you so much such perfect library.

I am new with your library I have conditional based some field, can I validate that as well ? if yes then how.

Thanks,
Ronak Amlani

**Comment by ragunathjawahar** [comment]
Thank you Ronak. Can you give me an example?

**Comment by ronakamlani** [comment]
Definitely my friend, 

Its not bug, I do not know the way to achieve..

Check below code and comment....

    @NotEmpty
    private EditText etQrcodeName;

    @NotEmpty
    private EditText etStartDate;

    @NotEmpty
    private EditText etEndDate;

    //Configuration
    private Spinner spQrcodeType;

    @NotEmpty
    private EditText etQrcodeData;


	/******************************************************************/
    //I am looking for validate to all but all below given section are condition based, that means either Data section
    // Or Access location section need to validate not both, this decision will taken runTime depend on one dropdown parameter.


    //Data section.. 
    private Button btnAccessLocation;
    private int lat;
    private int lng;

    //Access location section..
    private Spinner spAccessGroup;

    private EditText etWebsiteName;
    private EditText etWebsiteUrl;

    private EditText etOpeningTIme;
    private EditText etClosingTIme;



	@Override
    public void onValidationSucceeded() {

        //Get data from server..
        saveParticipate();

    }

    @Override
    public void onValidationFailed(List<ValidationError> errors) {
        for (ValidationError error : errors) {
            View view = error.getView();
            String message = error.getCollatedErrorMessage(this);

            // Display error messages ;)
            if (view instanceof EditText) {
                ((EditText) view).setError(message);
            } else {
                Toast.makeText(this, message, Toast.LENGTH_LONG).show();
            }
        }
    }


Thank you so much for your quick answer..

**Comment by ragunathjawahar** [comment]
You need to write a `QuickRule` to validate the fields based on the value selected in your `Spinner`.

**Comment by ronakamlani** [comment]
Do you means my custom rules ?

**Comment by ragunathjawahar** [comment]
That's right.

**Comment by ronakamlani** [comment]
Please tell me syntax, I can not found QuickRule.


Thank thank you so much for your time.

Regards,
Ronak Amlani.

**Comment by eklam** [comment]
@ronakamlani You can refer to[ this page ](https://github.com/ragunathjawahar/android-saripaar/wiki/Using-QuickRules)

**Comment by ragunathjawahar** [comment]
@eklam Thanks for the wiki. I just  built on top of it.

**Comment by ronakamlani** [comment]
I see you have created articles for me thank you so much man for that..

Thanks..
:)
