### ISSUE TITLE
 Does it work with Floating labels?

### ISSUE THREAD

**Issue by kamilwlf** [ragunathjawahar/android-saripaar#118]
Does it work with Floating labels?

**Comment by ragunathjawahar** [comment]
Yes, it does. You just have to supply a suitable adapter.

```java
ViewDataAdapter<FloatLabeledEditText, String> fletStringAdapter = new ViewDataAdapter<>() {

    @Override
    public String getData(FloatLabeledEditText flet) throws ConversionException {
        return flet.getEditText().getText().toString();
    }
};

mValidator.registerAdapter(FloatLabeledEditText.class, fletStringAdapter);
```

Depending upon the rule, you have to supply adapters that return the appropriate data type.

**Comment by kamilwlf** [comment]
I had to modify your code, leave it or something can be better?    

   ViewDataAdapter<TextInputLayout , String> fletStringAdapter = new ViewDataAdapter() {
            @Override
            public Object getData(View view) throws ConversionException {
                TextInputLayout textInputLayout= (TextInputLayout)view;
                return textInputLayout.getEditText().getText().toString();
            }
        };

**Comment by kamilwlf** [comment]
ok, works mycode:

    validator.registerAdapter(TextInputLayout.class,
                new ViewDataAdapter<TextInputLayout, String>() {
                    @Override
                    public String getData(TextInputLayout flet) throws ConversionException {
                        return flet.getEditText().getText().toString();
                    }
                }
        );

**Comment by ragunathjawahar** [comment]
OK great!

**Comment by cendelinova** [comment]
Hi,
I am new to Android. Could you provide more information about it? I would like to use your library to validate my inputs and use Textinpulayout. I am not sure how to set error under the input. Now I am validating next to the input which I do not like it. 

`  validator.registerAdapter(TextInputLayout.class,
                new ViewDataAdapter<TextInputLayout, String>() {
                    @Override
                    public String getData(TextInputLayout flet) throws ConversionException {
                        return flet.getEditText().getText().toString();
                    }
                }
        );`

Also I created text watcher 
` private TextWatcher registerTextWatcher() {
        TextWatcher validationTextWatcher = new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence charSequence, int i, int i1, int i2) {
            }

            @Override
            public void onTextChanged(CharSequence charSequence, int i, int i1, int i2) {
            }

            @Override
            public void afterTextChanged(Editable editable) {
                validator.validate();
            }

        };
        return validationTextWatcher;
    }`

Then I use for my inputs 

`inputEmail.addTextChangedListener(validationTextWatcher); inputPassword.addTextChangedListener(validationTextWatcher);`

But it is not working.

Thanks for any advices
