### ISSUE TITLE
Error messages not placed correctly

### ISSUE THREAD

**Issue by draskosaric** [ragunathjawahar/android-saripaar#129]
Hi, 

I created `LinearLayout` and put `TextInputLayout` widgets one under the other. Then I implemented custom adapter and everything works fine, but first error message after validation is not placed correctly. I feel that it may have something to do with keyboard that raises up, but maybe I am wrong. 

On first screenshot email is empty and appropriate message is shown, but put upper than it should and it covers that little red exclamation mark.

![2015-12-13 21 02 07](https://cloud.githubusercontent.com/assets/2921485/11769382/5cd44c36-a1e6-11e5-8980-cfd976e18bd9.png)
On next, I put some correct text in email field, but now error message for password does the same thing.
![2015-12-13 21 02 20](https://cloud.githubusercontent.com/assets/2921485/11769401/8d550c24-a1e6-11e5-8e88-0f7f6078713e.png)

Can you please tell me what am I doing wrong?

Thanks! Btw, this library is a-w-e-s-o-m-e.

**Comment by rzhik** [comment]
Try to use `setError()` method of your `TextInputLayout` instead of `EditTex`.

**Comment by shanuka** [comment]
1+

**Comment by ragunathjawahar** [comment]
@draskosaric how are you displaying error messages? Did you try @rzhik's solution?

**Comment by draskosaric** [comment]
Yes, I did, but with no luck. Anyway I used custom EditText control and solved the problem that way.

**Comment by ragunathjawahar** [comment]
OK great! Closing this because this isn't related to the library.
