### ISSUE TITLE
Validating hidden fields

### ISSUE THREAD

**Issue by HermannK** [ragunathjawahar/android-saripaar#130]
Hi Ragunath, 

I understand from reading other issues that it is a feature. However, we've got a view that is layouted similar to an expandable list where the user can collapse sections of the view. Within these partly collapsed sections are input fields that we need to include in the validation. By collapsing a section all subviews are hidden (visibility=GONE), including the input fields.

I understand from your code that the check "if (view.isShown() & view.isEnabled()) ..." is fix coded and there is no configurable item that enables or disables this feature. 

What do you think of making this configurable like "checkHidden = true" on rule level (with a default of false) or so?
Or woudn't it be sufficient to change that if statement to "if (view.isEnabled())". Somebody who wants to exclude hidden fields from validation could still disable them. 

As for now we are using @NotEmpty checks only on that view.

Any help is appreciated. 

Cheers
Hermann

**Comment by draskosaric** [comment]
I am positive that setError() will work on hidden EditText. If this option is enabled you should definitely try to develop some other way of error notification in `public void onValidationFailed(List<ValidationError> errors)` for this scenario.

**Comment by HermannK** [comment]
We have got an implementation of onValidationFailed that does not use setError(). But even if - that does not help much when the hidden fields are not even validated, though?

**Comment by draskosaric** [comment]
You are right about that. I think that would be useful feature too. So, where do I sign in? :)

**Comment by ragunathjawahar** [comment]
We could have a configuration that allows validation of hidden fields. Will add it.

**Comment by HermannK** [comment]
Great news. Thanks.

**Comment by HermannK** [comment]
@ragunathjawahar Do you have any idea about the timeframe yet? 
Thanks
Hermann

**Comment by BenjaminZaiser** [comment]
Hi @ragunathjawahar I'm also interested in this feature; would be great if you could implement it or at least give me a timeframe, when it will be on the master.
Thanks.

**Comment by ragunathjawahar** [comment]
@BenjaminZaiser this week :)

**Comment by ragunathjawahar** [comment]
Use `validator.validateInvisibleViews(true);`, pending release.

**Comment by grabcityinfo** [comment]
Hello @ragunathjawahar 

I'm using 2.0.3 but don't see that method "validator.validateInvisibleViews(true)"

Which release has that feature?

**Comment by xrnd** [comment]
@ragunathjawahar when is the release planned for "validator.validateInvisibleViews(true)"? Facing similar issue.

**Comment by benchakalaka** [comment]
Hello, any update on this feature?
