### ISSUE TITLE
radiogroup notempty?

### ISSUE THREAD

**Issue by u007** [ragunathjawahar/android-saripaar#131]
is there anyway for us to prompt radio group as required?

**Comment by ragunathjawahar** [comment]
You can use the `@Checked` annotation.

**Comment by u007** [comment]
hi, can this be noted in the readme?

**Comment by ragunathjawahar** [comment]
Will add it to the Wiki.

**Comment by u007** [comment]
Awesome man, great library +1

**Comment by ragunathjawahar** [comment]
Thank you :)
