### ISSUE TITLE
Validate custom View with String and Int

### ISSUE THREAD

**Issue by MickaelRomaniello** [ragunathjawahar/android-saripaar#137]
Hi, 
I'm using this library for my EditText <https://github.com/rey5137/material> and I must use ViewDataAdapter for Android Saripaar.
I used this post for solve one of my problem <https://github.com/ragunathjawahar/android-saripaar/issues/93>. 

I can now use Annotation **Email** but I can't use **MAX** or **MIN** because I have this error `java.lang.UnsupportedOperationException: To use 'com.mobsandgeeks.saripaar.annotation.Max' on 'com.rey.material.widget.EditText', register a 'com.mobsandgeeks.saripaar.adapter.ViewDataAdapter' that returns a 'java.lang.Integer' from the 'com.rey.material.widget.EditText'.`

How I can make this possible ? By using this EditText with Email and Min or Max ? 
I have no idea to make the return line. 

I have try this :
````java
public class AdapterMaterialEditTextInteger implements ViewDataAdapter<EditText, Integer> {
    @Override
    public Integer getData(EditText editText) throws ConversionException {
        //return editText.getText().toString();
    }
}
````

Thank you for your help :)

**Comment by gauravsak** [comment]
What do you exactly want to do?

Are you trying to use `@Email` and `@Min/@Max` on the same `EditText`? Well I don't know why you would want to do that because EmailRule is a string validator whereas MinRule/MaxRule are integer validators.

Please post some code so that its easier to understand you use case. Thanks.

**Comment by ragunathjawahar** [comment]
@MickaelRomaniello you are on the right track, check this [example](https://github.com/ragunathjawahar/android-saripaar/blob/master/saripaar/src/main/java/com/mobsandgeeks/saripaar/adapter/TextViewIntegerAdapter.java). After you have created your adapter you should register it by doing the following,

````java
validator.registerAdapter(com.rey.material.widget.EditText.class, new AdapterMaterialEditTextInteger());
````
