### ISSUE TITLE
How to override an annotation

### ISSUE THREAD

**Issue by Zapnologica** [ragunathjawahar/android-saripaar#138]
How can I possibly override a rule / annotation to return a better error message?

I currently make use of the following password annotation:

````java
@Password(min = 6, scheme = Password.Scheme.ALPHA_NUMERIC_MIXED_CASE)
@NotEmpty
EditText et_password;
````

However it simply replies invalid password which does not help end users one tiny bit.

How can I implement my own password rule, or even better extend the current saripaar one to actually return.

You need to have a upper case letter,
You need to have a lower case letter,
You need to have a digit
etc?

And If there is anyway which I could actually contribute this towards the saripaar project I would gladly be willing to help. However I have never contributed to an open source project and would need some guidance into it all.

Thanks

**Comment by gauravsak** [comment]
@Zapnologica You can use the `message` attribute on the `Password` annotation to give a custom message. Currently, different messages based on different validation errors are not supported.

If you want to write you own rule, you can do it like [PasswordRule.java] (https://github.com/ragunathjawahar/android-saripaar/blob/master/saripaar/src/main/java/com/mobsandgeeks/saripaar/rule/PasswordRule.java)

**Comment by ragunathjawahar** [comment]
Yes, like @gauravsak said. Use the `message` or `messageResId` attribute to specify your own messages.
