### ISSUE TITLE
Latest Version : Add Rules programmatically

### ISSUE THREAD

**Issue by rohanmahale** [ragunathjawahar/android-saripaar#145]
I'm trying to add this as a dependency using gradle. What is the latest version? 

Also, If I need to add rules programmatically for specific views, how do I go about it?

**Comment by ragunathjawahar** [comment]
You can always check the [releases](https://github.com/ragunathjawahar/android-saripaar/releases) tab for the latest version. To add rules programatically please follow this [issue](https://github.com/ragunathjawahar/android-saripaar/issues/127).
