### ISSUE TITLE
Stereotype annotations for grouping

### ISSUE THREAD

**Issue by marcin-jelenski** [ragunathjawahar/android-saripaar#152]
Hi,

I wonder if it is possible to add 
`@Target({ElementType.FIELD, ElementType.ANNOTATION_TYPE})`
instead of
`@Target(ElementType.FIELD)`

to standard library annotations (eg. NotEmpty, Passwrod, Email).

It would be nice to create "stereotype annotations" for grouping repeatable parameters, like

```
@NotEmpty(messageId = R.string.invalid_empty)
@Password(messageId = R.string.invalid_password)
public @inferface NonEmptyPassword() { }
```

Best regards,
Marcin

**Comment by ragunathjawahar** [comment]
@marcin-jelenski This is an interesting idea. Let's bring it in for `2.1.0`.
