### ISSUE TITLE
How to validate only 5 selected fields for a button click? 

### ISSUE THREAD

**Issue by RethinavelPillai** [ragunathjawahar/android-saripaar#161]
Hello Ragunath, 
        I am really happy to use your library. It really avoids boilerplate codes. I have a situation here.

See, Say for ex. I have 10 Edittext in an activity. I added attributes for all the fields. I want to validate first 5 fields on some X button click(rest 5 fields are hidden here). After that i hide that first 5 Edittexts and again rest 5 fields has to be validated on the same X button click? 

Is there any option to do that.

**Comment by ragunathjawahar** [comment]
You should group your view using different controller classes and use a `Validator` per controller. See the discussion in issues #104  and #134.
