### ISSUE TITLE
Make validateAfter() possible

### ISSUE THREAD

**Issue by sneps85** [ragunathjawahar/android-saripaar#162]
I have a layout:
- email
- submitemail
- phone
- submitphone

i need to validate email only on submitemail press and phone only on submitphone press.

How to do that? What is the difference between validateBefore() and validateTill()?

**Comment by ragunathjawahar** [comment]
See my comment to issue #161.

`validateBefore()` and `validateTill()` are supposed to be used with ordered fields (Your views must use the `@Order` annotation). `validateBefore(View)` will validate fields that are before the current view, `validateTill(View)` will validate all the fields till the current view.
