### ISSUE TITLE
multiply rules on Same View

### ISSUE THREAD

**Issue by shkhaksar** [ragunathjawahar/android-saripaar#165]
i have one edit text, i want to validate it using two validator rules, but i want to get success callback when only one rules getting true.
in my edit text user can input Phone Number or Email. 
BTW thank you for this awesome Lib.

**Comment by rjoncontract** [comment]
@shkhaksar You have to use a custom rule (quick rule or annotation) at the moment. There will be support for the `@Or` annotation in the future.

**Comment by ragunathjawahar** [comment]
Duplicate #61
