### ISSUE TITLE
New Saripaar Version?

### ISSUE THREAD

**Issue by PranKe01** [ragunathjawahar/android-saripaar#167]
Hi,
when will the new Saripaar version be released? The version 2.0.3 is more than a year old :|

**Comment by ragunathjawahar** [comment]
I don't have a timeline on this. The latest snapshot `2.1.0-SNAPSHOT` is available in the snapshot repo (uploaded today).

**Comment by Fatimamostafa** [comment]
It's so confusing when you write Latest version on doc. Why not providing the exact version number?
