### ISSUE TITLE
Text validation not visible

### ISSUE THREAD

**Issue by maxbax** [ragunathjawahar/android-saripaar#168]
I'm using your library to check if some fields are not empty. With the same annotation (@NotEmpty(messageResId = R.string.error_field_required)) in a normal TextInputEditText field the popup (black with white text) appears, but in on other  TextInputEditText (inside a toolbar) I can see a black popup without text (or with black text). How can I force the style of the popup trying to change colors?
Thanks

**Comment by rjoncontract** [comment]
@maxbax Saripaar doesn't display error messages. Please check SO. Also, adding screenshots when dealing issues helps when discussing UI issues.

**Comment by maxbax** [comment]
Thanks for the reply. I think there is a style problem. I attach two screenshot of the same app. The wrong style (text color) is in the actionbar edit text. How can I change or force that color?
Thanks

![screenshot_20161026-085350](https://cloud.githubusercontent.com/assets/7492935/19716221/df961618-9b5a-11e6-8f9f-34590bbb6060.png)
![screenshot_20161026-085509](https://cloud.githubusercontent.com/assets/7492935/19716226/e6eebd66-9b5a-11e6-885b-ba46e636fadd.png)

**Comment by ragunathjawahar** [comment]
I have no idea, please check these SO posts,

http://stackoverflow.com/questions/14413575/how-to-write-style-to-error-text-of-edittext-in-android
http://stackoverflow.com/questions/14127710/change-background-of-edittexts-error-message
http://stackoverflow.com/questions/6745577/which-theme-attribute-changes-the-text-color-of-an-edittexts-error-message
