### ISSUE TITLE
 UnsupportedOperationException

### ISSUE THREAD

**Issue by RimonGazi** [ragunathjawahar/android-saripaar#172]
```
java.lang.UnsupportedOperationException: To use 'com.mobsandgeeks.saripaar.annotation.Checked' on 'android.widget.CheckedTextView', register a 'com.mobsandgeeks.saripaar.adapter.ViewDataAdapter' that returns a 'java.lang.Boolean' from the 'android.widget.CheckedTextView'.`
```

```java
@NotEmpty
@Checked(message = "You must agree to the terms.")
@BindView(R.id.genderCheckedTextView)
CheckedTextView mGenderCheckedTextView;

@Override
public void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    mValidator = new Validator(this);
    mValidator.setValidationListener(this);
}
```

**Comment by ragunathjawahar** [comment]
The error message is clear. You have to register a new `ViewDataAdapter` that returns a `Boolean` value. Check this [source](https://github.com/ragunathjawahar/android-saripaar/blob/master/saripaar/src/main/java/com/mobsandgeeks/saripaar/adapter/RadioButtonBooleanAdapter.java) to see how to write a new `ViewDataAdapter`.

You must also register the adapter to your `Validator` using `validator.registerAdapter(CheckedTextView.class, new CheckedTextViewBooleanAdapter())`.
