### ISSUE TITLE
Incorrect email validation 

### ISSUE THREAD

**Issue by viliamvolosv** [ragunathjawahar/android-saripaar#173]
`    @NotEmpty(messageResId = R.string.error_email_empty, sequence = 0)
    @Email(messageResId = R.string.error_email_invalid, sequence = 1)
    @InjectView(R.id.text_input_layout_email)
    @Order(1)
    TextInputLayout emailLayout;`

Email below pass like a correct email address
test@com
test@gm
test@gl

**Comment by viliamvolosv** [comment]
saripaar:2.0.3

**Comment by Sigvent** [comment]
Same issue detect there with test@.com

**Comment by ragunathjawahar** [comment]
Duplicate, see #115
