### ISSUE TITLE
How to use with butterknife @BindViews

### ISSUE THREAD

**Issue by abeemukthees** [ragunathjawahar/android-saripaar#174]
Hi, @ragunathjawahar. Thanks for the awesome library. It is working perfectly with ButterKnife @BindView annotations. But how to use saripaar when using :
```
@BindViews({R.id.editText1,R.id.editText2}) 
List<EditText> editTexts
```

**Comment by rjoncontract** [comment]
@abeemukthees, saripaar doesn't work with `@BindViews`, it is not meant to.
