### ISSUE TITLE
Print Error Message Sequencialy 

### ISSUE THREAD

**Issue by segunmicheal27** [ragunathjawahar/android-saripaar#177]
I am trying to print the error validation on the EdithText like this:
@NotEmpty
@Email
@BindView(R.id.edith) EdithText mEdith;

@NotEmpty
@Lenth(min = 6, Message= "Password must be 6 Characters")
@Password(min = 6, scheme = Password.Scheme.ANY)
private EditText passwordEditText;

but all the error just show once instead of one after the other e.g
if the EditText field is not empty
it should print the next one
and if the all rules is true it show only print one not all the same time

**Comment by Fahad-alkamli** [comment]
I had a similar issue, seems like the validation should stop after the first error but the library keeps checking for other annotations on the same view which leads to the problem you mentioned.

**Comment by segunmicheal27** [comment]
cool thanks @Fahad-alkamli and I wish to add to the class lib.

**Comment by segunmicheal27** [comment]
to solve the issue

**Comment by rjoncontract** [comment]
You should annotate all the fields with the `@Order` annotation. Then set `validator.setValidationMode(Mode.IMMEDIATE)`.

When this is done, the validation will stop at the first failure.

**Comment by segunmicheal27** [comment]
Thanks @rjoncontract  I will try it on my IDE now

**Comment by segunmicheal27** [comment]
@rjoncontract the suggestion actually works fine but i am having an issue again in ordering error rules within sequence rules it print all the error at the same

here is the code 

> // Fields
>     @NotEmpty(sequence = 1, message = "Message 1")
>     @Length(sequence = 2, min = 3, message = "Message 2")
>     @Order(1)
>     private EditText mNameEditText;
> 
>     @NotEmpty(sequence = 1, message = "Message 3")
>     @Length(sequence = 2, min = 10, message = "Message 4")
>     @Order(2)
>     private EditText mAddressEditText;
> 
>     @NotEmpty(sequence = 1, message = "Message 5")
>     @Email(sequence = 2, message = "Message 6")
>     @Order(3)
>     private EditText mEmailEditText;
> 
>     @NotEmpty(sequence = 1, message = "Message 7")
>     @Order(4)
>     private EditText mPhoneEditText;


so mNameEditText and other field where i have sequence  just print all the error at the same time, please i will love to how can i solve this problem
