### ISSUE TITLE
How to validate a Spinner?

### ISSUE THREAD

**Issue by anasanzari** [ragunathjawahar/android-saripaar#179]
Is there way to validate a spinner, ie to check whether user has chosen a particular value other than the default one?

**Comment by dxpelou** [comment]
@anasanzari did you find a solution to this?

**Comment by fabiomor** [comment]
You can accomplish this by providing a custom adapter to saripaar:

Define a new class implementing saripaar viewdataadapter:

`public class AppCompatSpinnerValidatorAdapter implements ViewDataAdapter<AppCompatSpinner, String> {

    @Override
    public String getData(AppCompatSpinner view) throws ConversionException {
        return view.getSelectedItem() != null ? view.getSelectedItem().toString() : "";
    }
}
`
and then in the class where you use the validar you register the new custom adapter:

 validator.registerAdapter(AppCompatSpinner.class, new AppCompatSpinnerValidatorAdapter());
