### ISSUE TITLE
Not validate an annotated field with a condition

### ISSUE THREAD

**Issue by victorblq** [ragunathjawahar/android-saripaar#186]
Is possible to not validate a password field annotated with @Password?
For exemple: I have a fragment that I use as PatientForm, it has a password field (Patient password). When I open the fragment clicking in the "Add" Button I need this field required, but when I open the fragment clicking in the "Edit" button I need it as a non required field, is this possible? How can I achieve that objetive without creating other fragment?

**Comment by mvssba** [comment]
Hi Victor, have you tried to validate with "validator.validate()";

**Comment by victorblq** [comment]
Hi mvssba, I think you don't understand, I need to NOT validate the field when the form is opened to edit a patient. It is validating at the save with `validator.validate()` but I want to not validate this field only even calling `validator.validate()` to validate other fields.

**Comment by Kikju** [comment]
I think you can do that similar like I did here https://github.com/ragunathjawahar/android-saripaar/issues/104#issuecomment-133822417

**Comment by ragunathjawahar** [comment]
As @Kikju pointed out, you need two controllers to do this. One with the `@Password` field annotation and another without it.
