### ISSUE TITLE
Digit Annotation is very confusing.

### ISSUE THREAD

**Issue by AlexCatch** [ragunathjawahar/android-saripaar#191]
I can't seem to get the digits annotation to work, I can't figure out for the life of me what the integer parameter its wants is.

Entering numbers into the EditText causes validation to fail with 'Must be a digit'

This is my code.

```java
    @NotEmpty
    @Order(value = 1)
    @Digits(integer = 2)
    @BindView(R.id.ageTextField)
    CoreEditText mAgeTextField;
```

**Comment by ragunathjawahar** [comment]
It is split into two parts `integer` and `fraction`. If you set `@Digits(integer = 2, fraction = 2)`. These are all valid - `1`, `1.1`, `1.12`, `23`, `23.2`, `23.25`

**Comment by malhobayyeb** [comment]
What is the meaning of `integer` in this context?

Does it mean the length of integers?

**Comment by ragunathjawahar** [comment]
@malhobayyeb yes it does.
