### ISSUE TITLE
How do I use it in Kotlin?

### ISSUE THREAD

**Issue by KimGenius** [ragunathjawahar/android-saripaar#198]
@NotEmpty
@Email
private EditText emailEditText;

@Password(min = 6, scheme = Password.Scheme.ALPHA_NUMERIC_MIXED_CASE_SYMBOLS)
private EditText passwordEditText;

@ConfirmPassword
private EditText confirmPasswordEditText;

@Checked(message = "You must agree to the terms.")
private CheckBox iAgreeCheckBox;

Kotlin gets the xml id and uses view, how do you handle this part?

**Comment by DamonChen117** [comment]
+1

**Comment by tapanrgohil** [comment]
any solution?

**Comment by codenameDuchess** [comment]
Using [Butterknife]() I am able to compile:

        @NotEmpty
        @Email
        @BindView(R.id.emailTextField)
         lateinit var emailTextField: EditText

        @NotEmpty
        @BindView(R.id.passwordTextField)
        @Password(min = 8, scheme = Password.Scheme.ALPHA_NUMERIC_MIXED_CASE)
         lateinit var passwordTextField: EditText

But when I call validator.validate() I receive an exception on Validator.java line 549 (Annotation[] annotations = field.getAnnotations();):

{AnnotationFactory} Method threw 'java.lang.NullPointerException' exception. Cannot evaluate libcore.reflect.AnnotationFactory.toString()

Any help you can offer is appreciated.

**Comment by ragunathjawahar** [comment]
Kotlin is not supported yet, would appreciate if someone sends a PR.
