### ISSUE TITLE
Validation not working second time in kotlin

### ISSUE THREAD

**Issue by munnadroid** [ragunathjawahar/android-saripaar#204]
Hi, I am using kotlin, saripaar and butterknife.
Suppose I have validation in submit button of FragmentA. When click in submit button its working fine. Then validation success,  app goes to FragmentB. Then again come back to FragmentA through back button. Then validation not working.

**Comment by rinav** [comment]
Same situation happening in my app as well.
In my case, the validation is happening inside a Dialog, built from [Material Dialog lib](https://github.com/afollestad/material-dialogs) 
Any guidance to solve the issue?

**Comment by cecyurbina** [comment]
I have the same problem, I am working with fragments using this library https://github.com/apl-devs/AppIntro, when come back to first fragment validation is always succeeded.

**Comment by munnadroid** [comment]
Not able to find the solution yet, I am planning to use https://github.com/inmite/android-validation-komensky library for validation.

Has anyone found the solution?

**Comment by munnadroid** [comment]
I solved the issue. I have all the saripaar initialization in basefragment like below:

>  if (validator == null) {
            validator = Validator(this)
            validator.setValidationListener(this)
        }

I removed the null check part and now its working fine.

> validator = Validator(this) 
validator.setValidationListener(this)
