### ISSUE TITLE
Support for library projects using R2

### ISSUE THREAD

**Issue by RiccardoM** [ragunathjawahar/android-saripaar#208]
Hi, thanks for the good work you did with this library. 

I'd like to propose a new feature that might be useful to all the people that wants to use this library inside a library project: adding the support of R2 inside your annotations, such as R2.string. 

ButterKnife already supports this by using an android-plugin, and is able to resolve ids inside library projects. I think that resolving strings could be great for the users that want to localize the messages using your library while developing android libraries for themselves.

**Comment by agicquel** [comment]
I need it too !

**Comment by abhishekBansal** [comment]
+1

**Comment by mnayef95** [comment]
+1

**Comment by mnayef95** [comment]
I have created an extensible annotation processing library that has these features
- Annotations based.
- Auto validation handling.
- Auto finds view by id.
- Support custom annotations.
- Support custom confirmation annotations, e.g. (Password and Confirm password).
- Support auto validation while typing.
- Support multi-module projects.
- Support Androidx.
- Support auto validation for custom views.

You can check it here: https://github.com/Winfooz/WinValidation
All contributions are welcome
