### ISSUE TITLE
No way to set order for custom rules

### ISSUE THREAD

**Issue by almozavr** [ragunathjawahar/android-saripaar#27]
Rules ordering is done on validation and custom rules adding occurs before. If so, custom rules always have more priority and that's not true.
Maybe, it's better to store `order` inside the `Rule`? So developer could add custom rules at runtime with proper priority.

**Comment by gmarques33** [comment]
Hi,

it`s possible to define the validation order with v2? If yes, how?

**Comment by ragunathjawahar** [comment]
@gmarques33, Just add the `@Order` annotation on all your views and add a quick rule to a `view` using `validator.put(View, QuickRule...)`

**Comment by jhonvidal** [comment]
before : validator.put(editText, Rules.required(Messages.ES_REQUERID_FIELD, true));
after : validator.put(View, QuickRule...)   ??? :|

**Comment by jhonvidal** [comment]
public class V_RadioGroupButton extends Rule<RadioGroup> {

    /**
     * Creates a new validation Rule.
     *
     * @param failureMessage The failure message associated with the Rule.
     */
    public V_RadioGroupButton(String failureMessage) {
        super(failureMessage);
    }

    @Override
    public boolean isValid(RadioGroup view) {
        view.setBackgroundColor(Color.WHITE);
        return view.getCheckedRadioButtonId() > 0;
    }

}

How to QuickRule? :( documentation please

**Comment by ragunathjawahar** [comment]
@jhonvidal You need to use v2 of the library to use ordering with `QuickRule`s.

**Comment by jhonvidal** [comment]
Thanks for responding, I'm using the v2, the problem is how to interpret the rules

**Comment by ragunathjawahar** [comment]
````java
@NotEmpty(sequence = 1)
@Email(sequence = 2)
// We are going to add a new QuickRule with a sequence number '3'
@Order(1)
private EditText mEmailEditText;

@Password
@Order(2)
private EditText mPassword;

@ConfirmPassword
@Order(3)
private EditText mConfirmPassword;

// ----------------------------------------------------------------------------------------------------------
// Possibly inside your onCreate(Bundle) method....
validator.put(mEmailEditText, AllowMyDomainOnlyQuickRule(3));

// ----------------------------------------------------------------------------------------------------------
// This is your quick rule, you can also instantiate an anonymous one
static class AllowMyDomainOnlyQuickRule extends QuickRule {
    // Code ...
}

````

Please check this [comment](https://github.com/ragunathjawahar/android-saripaar/issues/57#issuecomment-71428493) for a complete idea. Ordering and sequenceing is different in v2 from v1's `order` attribute.

**Comment by jhonvidal** [comment]
Great help, thank you very much !!!  @ragunathjawahar

**Comment by ragunathjawahar** [comment]
@jhonvidal You're welcome :)

**Comment by jhonvidal** [comment]
a detail : 
these lines :

@NotEmpty(sequence = 1)
@Email(sequence = 2)
@Order(1)
private EditText mEmailEditText;

--------------------------------------
How is interpreted programming in code? please an example of native rules
---------------------------------------
:) Thank

**Comment by jhonvidal** [comment]
I did this for required field :

```java
public class AllowRequiredQuickRule extends QuickRule {

    private static AllowRequiredQuickRule instance = null;

    public static AllowRequiredQuickRule getInstance(int i) {
        if (instance == null) {
            instance = new AllowRequiredQuickRule(i);
        }
        return instance;
    }

    public AllowRequiredQuickRule(int i) {
        super(i);
    }

    @Override
    public boolean isValid(View view) {
        return false;
    }

    @Override
    public boolean isValid(Object o) {
        EditText editText = (EditText) o;
        return !editText.getText().toString().isEmpty();
    }

    @Override
    public String getMessage(Context context) {
        return Messages.ES_REQUERID_FIELD;
    }
}
```

:+1:
