### ISSUE TITLE
Use string format in messageResId

### ISSUE THREAD

**Issue by akhy** [ragunathjawahar/android-saripaar#32]
I am not sure if "string format" is the right name for it. Basically what I need is an ability to do this.

in the rule:

``` java
@TextRule(order = 1, minLength = 5, messageResId = R.string.min_characters)
EditText username;
```

in the `strings.xml`:

``` xml
<string name="min_characters">%d characters minimum</string>
```

What I expect is validation error message should gives me message `5 characters minimum` but the actual result is `%d characters minimum` (the %d is not parsed).

Is there any way to achieve this? Hopefully this feature will be added in the future (if has not already)

Thanks

note: this proposed feature should also supports another validation annotations

**Comment by khafan** [comment]
@ragunathjawahar In our application we have lots of input fields with different minimum length required. I think it's ugly to have tens of similar message just for a varying number.
Can you consider it as a new feature?

**Comment by ragunathjawahar** [comment]
@khafan Can you raise this as a separate ticket, so that I can keep track of this?
