### ISSUE TITLE
Validating preferences items

### ISSUE THREAD

**Issue by mehdifanai** [ragunathjawahar/android-saripaar#4]
hi
Is there any chance that i can validate my apps preferences fields using saripaar? For example i need to not allow the user to enter no less than 100 on a EditTextPreference number field.
Any suggestions are welcome

**Comment by kunalbuddy** [comment]
@mehdifanai  didnt get you

**Comment by ragunathjawahar** [comment]
Saripaar will remain to be a UI validation library for the foreseeable future.
