### ISSUE TITLE
For canceling validations

### ISSUE THREAD

**Issue by siddhpatil6** [ragunathjawahar/android-saripaar#47]
if we one edittext validations are satisfied than skip other editexts validations,is it possible?

@Required(order = 1, message = "Please enter name")
private EditText et_name;
@Required(order = 1, message = "Please enter sirname")
private EditText et_sirname;

for example i need validation that either one of them feilds sholuld be validate
after that skip other feild for validations

**Comment by ragunathjawahar** [comment]
@siddhpatil6 please track this issue on ticket https://github.com/ragunathjawahar/android-saripaar/issues/61
