### ISSUE TITLE
call method instead of "message" in annotation[feature request]

### ISSUE THREAD

**Issue by Aexyn** [ragunathjawahar/android-saripaar#53]
hey, 
what I am proposing is , is there any way to call a local method from annotation. like

    @MinLength(value = 3, myMethodFailed(),myMethodPassed());
    private EditText mEditName;

I am saying this because in my app I am not showing inbuilt error message. and also on error, I turn the field red and on passed, I turn field back to normal. So I am asking if there is any way to implement any custom feature, please help me. Provide me some help with gist or something as I am noob to annotations
thankyou

**Comment by ragunathjawahar** [comment]
Like I already mentioned, I am working on a tiny DSL that will enable users to create dynamic messages. Method calls are too much overhead to handle. Follow #80 for updates on this feature.
