### ISSUE TITLE
@ConfirmPassword doesn't work

### ISSUE THREAD

**Issue by ragunathjawahar** [ragunathjawahar/android-saripaar#55]
This feature is not implemented yet.

**Comment by skoushan** [comment]
@ragunathjawahar if the feature is not yet implemented, please do not include it in the readme quickstart, or at least put a note.

**Comment by ragunathjawahar** [comment]
@skoushan Sorry for the trouble. Hope this helps https://github.com/ragunathjawahar/android-saripaar/commit/eccd57f942e82bd70b8b9954b740c1128b27ef4c

**Comment by skoushan** [comment]
@ragunathjawahar thanks, appreciate it. Looking forward to it being complete!

**Comment by ragunathjawahar** [comment]
@skoushan implemented, see 40e7172dfe581854cc7671b782f006479860a709 and snapshot is available!

**Comment by mehrad-rafigh** [comment]
@ragunathjawahar Where can I get the latest snapshot of this awesome library?

**Comment by ragunathjawahar** [comment]
@mehrad-rafigh The snapshots are available from maven central's snapshot repo. Checkout the [Readme](https://github.com/ragunathjawahar/android-saripaar/blob/master/README.md) for instructions.

**Comment by mehrad-rafigh** [comment]
I am familiar with your Readme file and I used that to setup my gradle file. Nevertheless the Annotation @ConfirmPassword is not working

**Comment by ragunathjawahar** [comment]
@mehrad-rafigh Ok great!
