### ISSUE TITLE
method is not !   validator.removeRulesFor(editText1);

### ISSUE THREAD

**Issue by jhonvidal** [ragunathjawahar/android-saripaar#63]
How do I remove the rules in V2?

**Comment by ragunathjawahar** [comment]
@jhonvidal v2 doesn't have a method for removing rules. I'm curious, can you explain your use case please?

**Comment by jhonvidal** [comment]
is this the case study:

```
            for (View view : selecciones) {
                final RadioButton radioButton1 = (RadioButton) view;
                radioButton1.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        if (radioButton1.getText().toString().equals(Messages.ES_LABEL_YES)) {
                              // validator.removeRulesFor(editText);//----- :(-------//
                        }

                        if (radioButton1.getText().toString().equals(Messages.ES_LABEL_NO)) {
                            validator.put(editText, AllowRequiredQuickRule.getInstance(iOrdenSelection1));
                            validator.put(editText, AllowIntegerMinQuickRule.getInstance(iOrdenSelection2,10));
                        }
                    }
                });
            }
```
is important to eliminate rules according to criteria,

please help !!

**Comment by jhonvidal** [comment]
@ragunathjawahar  I will thank the expectation...

**Comment by jhonvidal** [comment]
thanks, I'll wait anxiously...

**Comment by ragunathjawahar** [comment]
Implemented in https://github.com/ragunathjawahar/android-saripaar/pull/65. Will close this issue after I add test cases.

**Comment by ragunathjawahar** [comment]
@jhonvidal for changes, please check this [Validator](https://github.com/ragunathjawahar/android-saripaar/blob/354028d80c4a6cb8aef98282c479cafe937897d9/saripaar/src/main/java/com/mobsandgeeks/saripaar/Validator.java#L424-L426).

For the changeset, refer to https://github.com/ragunathjawahar/android-saripaar/commit/354028d80c4a6cb8aef98282c479cafe937897d9.
