### ISSUE TITLE
How can I enable rules in Java?

### ISSUE THREAD

**Issue by juliomarcos** [ragunathjawahar/android-saripaar#66]
I'm trying to follow this link (http://stackoverflow.com/questions/6613321/form-validation-library-for-android) without success.

I have a situation where I create views dynamically inflating them from a xml file. Is it possible to do that using annotation? If not, how can I do that in Java?

**Comment by ragunathjawahar** [comment]
I would suggest you to use `v1` for this particular scenario, because `v2` allows only annotations. However, I am keeping this issue open until built-in `QuickRule`s can be added using Java.

**Comment by ragunathjawahar** [comment]
Saripaar v2 contains a subset of validators from the [Commons Validator](http://commons.apache.org/proper/commons-validator/) project. You can find them [here](https://github.com/ragunathjawahar/android-saripaar/tree/master/saripaar/src/main/java/commons/validator/routines).

Use them in combination with a `QuickRule` to achieve the desired result.
