### ISSUE TITLE
when is v2 ready?

### ISSUE THREAD

**Issue by lucastan** [ragunathjawahar/android-saripaar#68]
Hi I have been waiting for many weeks for the stable version of v2 to arrive as I need to freeze the version  of my dependencies

**Comment by ragunathjawahar** [comment]
Hi @lucastan I really don't have a timeline on this. I put in as much time as I can, in open-source projects. We are using Saripaar v2 SNAPSHOT in ALL our production applications. There are a few minor features to be added. Besides that, there's isn't going to be changes in the existing API.

**Comment by lucastan** [comment]
If it is stable now, why not just freeze the version? When you add features
in the future, you can increase the version

**Comment by ragunathjawahar** [comment]
Follow #89
