### ISSUE TITLE
How to add custom scheme to password validation?

### ISSUE THREAD

**Issue by Lesilva** [ragunathjawahar/android-saripaar#69]
Hi, I wanted to add my custom scheme to password to do the validation. Can you show me how? @ragunathjawahar 

Thanks!

**Comment by ragunathjawahar** [comment]
@Lesilva, currently there isn't a way to add a scheme to the `@Password` annotation. However, can you tell me what you are trying to do? I'll be able to help you better.

**Comment by Lesilva** [comment]
Thanks for your reply. I'm using a regex to validation my password. I'll let you know how it goes and if I need any help. Thanks again.

**Comment by ragunathjawahar** [comment]
That's great :+1:
