### ISSUE TITLE
Remove final modifier from Validator

### ISSUE THREAD

**Issue by alexfu** [ragunathjawahar/android-saripaar#71]
Unless there is a specific reason the `Validator` class needs to be final, I'm proposing to drop the `final` modifier. 

Having it as `final` makes testing harder and makes it impossible to mock without another library (i.e. PowerMock)

**Comment by ragunathjawahar** [comment]
@alexfu Please check commit https://github.com/ragunathjawahar/android-saripaar/commit/78fa084b343c6dbb0713e5fee8a2a312770c1fd3. New snapshot available.

**Comment by alexfu** [comment]
@ragunathjawahar awesome, thanks!

**Comment by ragunathjawahar** [comment]
@alexfu You're welcome :+1:
