### ISSUE TITLE
More than 1 field annotated with 'com.mobsandgeeks.saripaar.annotation.Password

### ISSUE THREAD

**Issue by koolll** [ragunathjawahar/android-saripaar#75]
Hi i got two confirm password inside my apps.Here is my question How can i validate two password with two confirm password?

**Comment by ragunathjawahar** [comment]
@koolll, you need to use a `QuickRule` to accomplish your use case. Extend the `QuickRule` class and pass in the `@Password` `EditText` instance and then check it against your confirm password field.
