### ISSUE TITLE
Annotation @NoEmpty  No suggestions

### ISSUE THREAD

**Issue by Toqu3** [ragunathjawahar/android-saripaar#77]
Hello and thanks for the library
My question is
Because the "@oEmpty" appears to not exist, however if others, @checked, @email appear, etc.

Hola y gracias por la library
Mi pregunta es 
Por que el "@NoEmpty"  parece no existir, en cambio los otros si, como el @checked, @email, etc. 

.thanks

**Comment by ragunathjawahar** [comment]
Hi, can you please give me an use case? Thanks.
