### ISSUE TITLE
RadioGroup validator

### ISSUE THREAD

**Issue by ararog** [ragunathjawahar/android-saripaar#78]
It would be nice to allow RadioGroup validation with saripaar.

**Comment by ragunathjawahar** [comment]
@ararog Nice suggestion, will do.

**Comment by kitallis** [comment]
Is there an example of how you could custom implement this behavior?

**Comment by Zenyai** [comment]
+1

**Comment by createS0ftware** [comment]
I was just looking to find how to create a custom ViewDataAdapter for a radioGroup

Is there an example ?

Thanks

**Comment by ragunathjawahar** [comment]
You can make use of the `@Checked` annotation on a `RadioGroup`. The rule will pass if one of the `RadioButton`s is checked.

**Comment by ragunathjawahar** [comment]
@createS0ftware Can you check the latest snapshot and let me know if it works as expected?

**Comment by rishabutd** [comment]
@Checked
RadioButton rm;
@Checked
RadioButton rf;

I made a form in which I placed two radio buttons - Male and Female.

I have added the validation as shown above.

The problem is even after selecting one of the radio buttons, it still gives me a message (Must be checked).

Can you please explain this issue ?

**Comment by ragunathjawahar** [comment]
@rishabutd Place your `RadioButton`s inside a `RadioGroup` and put a `@Checked` annotation on it.

````java
@Checked
RadioGroup genderRadioGroup;
````

This should work. You should use your technique only on `CheckBox`es.

**Comment by rishabutd** [comment]
Yeah! I just tried that. Your code has been of great use.

**Comment by ragunathjawahar** [comment]
Thank you :)
