### ISSUE TITLE
open interface of Validator.removeAllRules() and Validator.getValidationListener()

### ISSUE THREAD

**Issue by edwardaa** [ragunathjawahar/android-saripaar#82]
Hi @ragunathjawahar , in case where adding/removing views dynamically, multiple `Validator` objects may be created, one for static views, others for dynamic views, and multiple ValidationListener are created. For validators of dynamic views, the `Validator.removeAllRules()` or `Validator.getValidationListener()` is useful

**Comment by ragunathjawahar** [comment]
Could you please show some code?

**Comment by edwardaa** [comment]
thanks, at last I have to use a hack way to  that, but it works
