### ISSUE TITLE
It will be great to have Phone and pincode validation 

### ISSUE THREAD

**Issue by hardikamal** [ragunathjawahar/android-saripaar#83]
It will be great to have Phone and pincode validation.... Thanks for the awesome library

**Comment by inktomi** [comment]
What do you mean by pincode validation? Could you use @NotEmpty @Digits?

For phone numbers you could use @Pattern with a regex to match a phone number in the format you're expecting.

**Comment by ragunathjawahar** [comment]
There is no standard format for telephone numbers and pin codes (widely known as zip code in other countries). Both of these differ from country to country. @hardikamal You could use the annotations just like @inktomi mentioned or you could also create your own custom annotations for reusability. I also should bring to your attention, the lesser know [Saripaar X](https://github.com/ragunathjawahar/saripaar-x) project for country specific annotations. You can send pull requests for region-specific annotations.
