### ISSUE TITLE
Domain validator missing hundreds of TLDs

### ISSUE THREAD

**Issue by Philio** [ragunathjawahar/android-saripaar#84]
The list of domains in the domain validator is somewhat lacking...

https://github.com/ragunathjawahar/android-saripaar/blob/master/saripaar/src/main/java/commons/validator/routines/DomainValidator.java#L220

See: http://www.newtldlist.com/

**Comment by ragunathjawahar** [comment]
@Philio Thanks for the link. Also reported in #81

**Comment by ragunathjawahar** [comment]
Snapshot available.
