### ISSUE TITLE
Fragment crash No rules found. You must have at least one rule to validate.

### ISSUE THREAD

**Issue by pawarlalit29** [ragunathjawahar/android-saripaar#85]
This is the sample fragment. Its is not working on fragment but working fine if converted to activity

        package com.sample.mysample.fragments;

       import android.os.Bundle;
       import android.support.v4.app.Fragment;
       import android.support.v4.app.FragmentManager;
       import android.util.Log;
       import android.view.LayoutInflater;
       import android.view.View;
       import android.view.ViewGroup;
       import android.widget.Button;
       import android.widget.EditText;
       import android.widget.Toast;

       import com.sample.mysample.AppConstant;
       import com.sample.mysample.R;
       import com.sample.mysample.activities.MainActivity;

       import com.mobsandgeeks.saripaar.ValidationError;
       import com.mobsandgeeks.saripaar.Validator;
       import com.mobsandgeeks.saripaar.annotation.Email;

       public class Frag_Register extends Fragment implements View.OnClickListener{

    View view;

    @Email
    EditText edt_email;

    String str_email;
    Button btn_register;

    Validator validator;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

        view = (View) inflater.inflate(
                R.layout.fragment_register, container, false);

        edt_email = (EditText) view.findViewById(R.id.edt_email);
        
        btn_register = (Button) view.findViewById(R.id.btn_register);

        validator  = new Validator(getActivity());
        validator.setValidationListener(new Validator.ValidationListener() {
            @Override
            public void onValidationSucceeded() {
                Toast.makeText(getActivity(),"yahooooooooooo",Toast.LENGTH_LONG).show();
            }

            @Override
            public void onValidationFailed(List<ValidationError> errors) {
                for (ValidationError error : errors) {
                    View view = error.getView();
                    String message = error.getCollatedErrorMessage(getActivity());

                    // Display error messages ;)
                    if (view instanceof EditText) {
                        ((EditText) view).setError(message);
                    } else {
                        Toast.makeText(getActivity(), message, Toast.LENGTH_LONG).show();
                    }
                }
            }
        });

        btn_register.setOnClickListener(this);
        return view;
    }

    @Override
    public void onClick(View view) {
        switch (view.getId()){
            case R.id.btn_register:
                validator.validate();
                
                break;
            
        }
    }

    @Override
    public void onResume() {
        super.onResume();
        ((MainActivity) getActivity()).getSupportActionBar().setTitle(
                "Register");
    }

       }

**Comment by ragunathjawahar** [comment]
Change `validator  = new Validator(getActivity());` to `validator  = new Validator(this);`. You should pass the object that contains view field declarations.

**Comment by pawarlalit29** [comment]
thanks.

**Comment by JavierSolis** [comment]
I added an additional if for fragment support, I hope it helps

https://github.com/JavierSolis/android-saripaar/blob/673b7ea7174848b96bce1ae82fa2118d1af9f128/saripaar/src/main/java/com/mobsandgeeks/saripaar/Validator.java#L175

**Comment by dmaia17** [comment]
How i edit this class? @JavierSolis

**Comment by JavierSolis** [comment]
You can download the source code and add as a module, then you can edit it.
