### ISSUE TITLE
Validation edittext of recyclerview issue

### ISSUE THREAD

**Issue by TheLester** [ragunathjawahar/android-saripaar#87]
I have recycler view with edittext items,i added quick rules in bindview,  and when i call validate validation take place only on visible edittext. I think recycler unloads edittext or something ,but how i can resolve this?

**Comment by ragunathjawahar** [comment]
@TheLester how did you manage to resolve this?

**Comment by TheLester** [comment]
@ragunathjawahar I just deleted part of this checking (715 row in Validator,java) :
if (view.isShown() && view.isEnabled()) {....

**Comment by ragunathjawahar** [comment]
@TheLester out of curiosity, why did you choose to use a `RecyclerView`?

**Comment by TheLester** [comment]
@ragunathjawahar  cause i have list of input items(for some info detail) in my app, and user could add as many as he wants this detail items

**Comment by ragunathjawahar** [comment]
That's interesting :+1: Thanks.
