### ISSUE TITLE
Validation fails for credit card numbers with spaces in

### ISSUE THREAD

**Issue by Philio** [ragunathjawahar/android-saripaar#88]
If you enter a valid credit card number with spaces between groups e.g.

4111 1111 1111 1111 (Visa test card number)

Validation fails.

It's a fairly common practice to display credit card numbers this way for readability. Is there some way to trim the whitespace without adding a custom annotation/rule?

**Comment by ragunathjawahar** [comment]
Uploaded a new snapshot with the fix. Can you try it out and let me know if it works?

**Comment by Philio** [comment]
Thanks, I'll give it a try today and let you know if there are any issues.

**Comment by Philio** [comment]
I can confirm that it works with the latest snapshot, thanks!

**Comment by ragunathjawahar** [comment]
Thanks for confirming and you're welcome :)
