### ISSUE TITLE
Snapshots can be inconsistent, any ETA on a beta release?

### ISSUE THREAD

**Issue by Philio** [ragunathjawahar/android-saripaar#89]
We've been using the 2.0 snapshot for a while and for our usage it's been very stable and the minor issues that we've reported have been resolved very promptly so thanks for this.

As we near a public release of the phase of our application that uses the library it raises some concerns with continuing to use snapshots.

Unfortunately as there is no mechanism within Gradle to specify a specific snapshot build, we're either at the mercy of the Gradle cache (or have to ensure we regularly clear it to ensure the latest build) or we can set the `changing` flag but at the risk of potentially introducing breaking changes automatically.

Of course we can fork and/or use our own Maven repository, but if a more predictable release is on the horizon in the near future we'd prefer to use that.

**Comment by blazmag** [comment]
+1

**Comment by alpm** [comment]
+1

**Comment by ragunathjawahar** [comment]
I'll look into this as soon as I can. Most probably within the next couple of weeks.

**Comment by Philio** [comment]
It turns out that something was added to use a specific snapshot in Gradle 2.4:

https://docs.gradle.org/current/release-notes#depending-on-a-particular-maven-snapshot-version

I'll give this a try and see if it works, might solve the problem in the short term.

**Comment by Philio** [comment]
Can confirm that this works with Gradle 2.4:

`    compile 'com.mobsandgeeks:android-saripaar:2.0-20150608.165549-1'`

Also this works if you just want the latest (it forces the cache to be refreshed, which doesn't happen by default):

`    compile group: 'com.mobsandgeeks', name: 'android-saripaar', version: '2.0-SNAPSHOT', changing: true`

**Comment by ragunathjawahar** [comment]
@Philio This is good. Thanks for posting this tip. Would be beneficial to others in a similar situation :) I'll expedite this as much as I can.

**Comment by ragunathjawahar** [comment]
v2 has been released. Must take a while for it to appear on Maven Central. The release version is `2.0.0`

Release commit ID f8e96e8493a310a2a07d78e122bf88c29b2f9764
