### ISSUE TITLE
validation sequnce

### ISSUE THREAD

**Issue by viper83** [ragunathjawahar/android-saripaar#90]
Hello! And thank you for the lib.

I have a question for you.

I want to validate 2 EditText view's

    @Order(1)
    @NotEmpty(sequence = 1, messageResId = R.string.username_is_required)
    @Size(sequence = 2, min = 5, messageResId = R.string.username_too_short)
    EditText etUsername;
    @Order(2)
    @NotEmpty(sequence = 1, messageResId = R.string.email_address_is_required)
    @Email(sequence = 2, messageResId = R.string.email_is_not_valid)
    EditText etEmail;

The goal of my validation is next:
 - When i click the Submit button, validator should check the fields is not empty first and stop validatio, but not check the size of the field at this step.
- Validator shoul check the fields size only when fields are not empty.

Is it possible? Now validator check NotEmpty rule and Size rule at one step, but i want to check size and not empty view on two steps.

Thanks!

**Comment by ragunathjawahar** [comment]
Use the `IMMEDIATE` mode for validation. This is what you are looking for `mValidator.setValidationMode(Mode.IMMEDIATE);`

**Comment by viper83** [comment]
Thanks!
Sorry, i forgot to say, but i already use this mode
    validator.setValidationMode(Validator.Mode.IMMEDIATE);

And the issue reproduced with this mode. If rge etUsername is empty and i call validator.validate(), i have 2 error messages - message about username is required and message about username is too short.

For me the sequence options affects only the error messages order in the ValidationError list.

**Comment by ragunathjawahar** [comment]
@viper83 Yes that's right. You get a list of errors for the `etUsername` field. Just display the first error and ignore the rest.

**Comment by viper83** [comment]
@ragunathjawahar ok, thanks!
I will use a list of messages and get only first of them. I just thought there is a option out of the box.

**Comment by ragunathjawahar** [comment]
@viper83 You're welcome.
