### ISSUE TITLE
Validating methods

### ISSUE THREAD

**Issue by m-radzikowski** [ragunathjawahar/android-saripaar#91]
Currently to make custom validation we have to make for example:
```java
validator.put(nameView, new QuickRule<EditText>() {
			@Override
			public boolean isValid(EditText view) {
				return !takenNames.contains(view.getText().toString());
			}

			@Override
			public String getMessage(Context context) {
				return getString(R.string.error_duplicated);
			}
		});
```
in the `onCreate` / `onCreateView` / similar method. It would be great if we could extract this logic into separate method and annotate it, just like in Java Validation API. For example:
```java
@AssertTrue(res = R.id.name, messageResId = R.string.error_duplicated)
private boolean nameIsUnique() {
	return !takenNames.contains(view.getText().toString());
}
```
or to leave annotations signatures as they are (to not add `res` parameter) it could be new annotation only for methods:
```java
@Valid(res = R.id.name, messageResId = R.string.error_duplicated)
private boolean nameIsUnique() {
	return !takenNames.contains(view.getText().toString());
}
```

**Comment by ragunathjawahar** [comment]
@m-radzikowski This looked like an interesting idea and I was pondering about this for a while after you raised this issue. We won't be proceeding with this for two reasons.

1. Discourages code reuse.
2. Overuse of annotations, will have to add support for ordering, sequencing and the methods will be scattered all over the Activity making it hard to maintain and debug.
