### ISSUE TITLE
validate custom view 

### ISSUE THREAD

**Issue by rexi1r** [ragunathjawahar/android-saripaar#93]
hi i need validate custom view.i know that i can use ViewDataAdapter but how?

**Comment by LuisBurgos** [comment]
Hi @rexi1r, I had the same problem with https://github.com/rey5137/material trying tu use the EditText widget from that library, here's what worked for me:

1. Create an adapter for the widget which implements ViewDataAdapter
   * In my case, I named **AdapterMaterialEditText:**
    ```java
package com.adapter;

import com.mobsandgeeks.saripaar.adapter.ViewDataAdapter;
import com.mobsandgeeks.saripaar.exception.ConversionException;
import com.rey.material.widget.EditText;

public class AdapterMaterialEditText implements ViewDataAdapter<EditText, String> {
      @Override
      public String getData(EditText editText) throws ConversionException {
          return editText.getText().toString();
      }
}
```
2. Register the new adapter to Validator
   ```java
Validator.registerAdapter(EditText.class, new AdapterMaterialEditText());
```

   * In my case, I put it after creating an instance of Validator, like this:
   ```java
validator = new Validator(this);
Validator.registerAdapter(EditText.class, new AdapterMaterialEditText());
validator.setValidationListener(this);
```

*I used these as reference:*

For the **Adapter** - https://github.com/ragunathjawahar/android-saripaar/blob/master/saripaar/src/main/java/com/mobsandgeeks/saripaar/adapter/ViewDataAdapter.java

For the **Register** - https://github.com/ragunathjawahar/android-saripaar/blob/master/saripaar-tests/src/main/java/com/mobsandgeeks/saripaar/tests/ui/CustomViewDataAdapterActivity.java

**Comment by ragunathjawahar** [comment]
@rexi1r If you want to use existing annotations with your custom views, use the solution mentioned by @LuisBurgos. If you want to use a custom annotation, you must write your own annotation and a `ViewDataAdapter`.

Here's a [SO Post](http://stackoverflow.com/questions/21405645/adding-a-custom-annotation-to-android-saripaar) on how to write custom annotations.

**Comment by amanthaIsuru** [comment]
Great explanation. thanks @LuisBurgos

**Comment by JavierSolis** [comment]
Thanks @LuisBurgos, I tried it and it worked, but it gave me an error in the release by the proguard, so, if you use proguard, keep the adapter

`
#Android Saripaar
-keep class com.mobsandgeeks.saripaar.**
-keep class com.mobsandgeeks.saripaar.** {*;}

-keep class <package of adapter>.** { *; }
`
