### ISSUE TITLE
Provide a variant of @Pattern annotation which accepts java.util.rexex.Pattern

### ISSUE THREAD

**Issue by dimsuz** [ragunathjawahar/android-saripaar#95]
Currently `@Pattern` annotation supports only `String` regex parameter, but sometimes it is handy to pass some predefined `Pattern`. For example android has an utility [Patterns](https://developer.android.com/reference/android/util/Patterns.html) class which exposes a number of patterns as static `Pattern` instances.

It would be great to have an ability to just pass them to `@Pattern` annotation.

I could provide a PR for this, but I am not sure at how is it best to proceed (if you agree with this feature): by creating some new annotation, or by extending `@Pattern` with some new field or by using some other approach?

**Comment by ragunathjawahar** [comment]
@dimsuz I don't see too many benefits that this PR / feature would add to the library. There are 6 patterns out of which 5 are already present in Saripaar. The only missing regex is *phone* which you can copy from the [source code](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/util/Patterns.java) itself.

```java
public static final Pattern PHONE
        = Pattern.compile(                      // sdd = space, dot, or dash
                "(\\+[0-9]+[\\- \\.]*)?"        // +<digits><sdd>*
                + "(\\([0-9]+\\)[\\- \\.]*)?"   // (<digits>)<sdd>*
                + "([0-9][0-9\\- \\.]+[0-9])"); // <digit><digit|sdd>+<digit>
```
