### ISSUE TITLE
Validator.registerAdapter() should not be static (or leaks are easy to follow)

### ISSUE THREAD

**Issue by dimsuz** [ragunathjawahar/android-saripaar#97]
I beleive that it would be better to make `Validator.registerAdapter()` non-static method.

I just had whole `Activity` context leaked because of this method is static.
If you do something like this in your activity:

```
void onCreate() {
  Validator.registerAdapter(MyCustomView.class, new ViewDataAdapter<MyCustomView, String>() {
    public String getData(MyCustomView view) {
       return view.getCustomText();
    }
   validator = new Validator();
}
```

then you automatically leak your Context, because it gets captured by anonymous class.
And using anonymous classes for this kind of things is very common.
So using static here makes it very easy to introduce a leak.

Besides by looking at the sources I don't see why this method needs to be global.
`Validator` class seems to be designed to be used in local scope, i.e. inside an activity lifetime, so it seems that registerAdapter should live in that scope too, i.e. be non static.

**Comment by ragunathjawahar** [comment]
You're right. Feel free to send a PR.

**Comment by dimsuz** [comment]
Ok!

**Comment by ragunathjawahar** [comment]
Fixed by 350a42cddd2470a2c5404407bb9a22eee98c4c73

**Comment by ragunathjawahar** [comment]
@dimsuz Thank you :+1:

**Comment by dimsuz** [comment]
you are welcome :)
do you plan to upload a new snapshot to sonatype in near future?

**Comment by ragunathjawahar** [comment]
Thanks for reminding. Just uploaded a new snapshot.

**Comment by dimsuz** [comment]
Great, thank you!

**Comment by dimsuz** [comment]
@ragunathjawahar somehow the current snapshot became `.aar` instead of `.jar` which it was in previous versions. Is this intentional or some issue has led to this? I unpacked `.aar` and its res/ folder is empty, so seems like a build misconfiguration?..

See https://oss.sonatype.org/#nexus-search;quick~saripaar

**Comment by ragunathjawahar** [comment]
@dimsuz I have to update my maven publishing script, both `.aar`s and `.jar`s are being uploaded. Did you mention `@aar` in your dependency?

**Comment by dimsuz** [comment]
No, I tried to download directly from the above link. Currently I have `android-saripaar.jar` placed directly in my `libs/` folder (due to various reasons) - that's why I noticed that it changed from `.jar` to `.aar`...

**Comment by ragunathjawahar** [comment]
![capture](https://cloud.githubusercontent.com/assets/1141970/8953847/1565e97a-35ff-11e5-8031-60505c7f2b48.PNG)

**Comment by dimsuz** [comment]
oh, thank  you. didn't know about this!

**Comment by dimsuz** [comment]
One more thing: somehow the change which was fixed by this issue is not present in the snapshot - `Validator.registerAdapter` is still static. Not sure why. I double checked by decompiling a `Validator.class` from the above `.jar` and it's indeed still static :)

**Comment by ragunathjawahar** [comment]
:smiley: I didn't pull before I uploaded the archives. Can you check now?

**Comment by dimsuz** [comment]
Everything is perfect now :) thanks.
