### ISSUE TITLE
What is the current version ?

### ISSUE THREAD

**Issue by createS0ftware** [ragunathjawahar/android-saripaar#99]
HI 

dependencies {
    compile 'com.mobsandgeeks:android-saripaar:2.0-SNAPSHOT'
}

This call does not work . What is the current version ? How is version 1 defined ?

dependencies {
    compile 'com.mobsandgeeks:android-saripaar:1.0
}

also does not work

Thanks

**Comment by ragunathjawahar** [comment]
You haven't included the snapshot URL. Check the Snapshots section in Readme. Check releases (https://github.com/ragunathjawahar/android-saripaar/releases) to find the list of available versions.
